// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Task struct {
	ID               int64
	Title            string
	Description      sql.NullString
	Done             bool
	CreationDate     time.Time
	ModificationDate time.Time
	DeletionDate     sql.NullTime
}

type TasksFt struct {
	Title       string
	Description string
}
